### ISSUE TITLE
The 'CommandShowTomatoStatusBarPackage' did not load correctly. in VS 2019 v 16

### ISSUE THREAD

**Issue by praised** [djfoxer/healthyWithVS#1]
| LegacySitePackage failed for package [CommandShowTomatoStatusBarPackage]Source: 'djfoxer.HealthyWithVS' Description: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.   at djfoxer.HealthyWithVS.Services.MainService.TogglePomodoroTimerStatusBar() in C:\Users\Scorpion\Desktop\healthyWithVS-master\djfoxer.HealthyWithVS\djfoxer.HealthyWithVS\Services\MainService.cs:line 25   at djfoxer.HealthyWithVS.CommandShowTomatoStatusBar..ctor(Package package) in C:\Users\Scorpion\Desktop\healthyWithVS-master\djfoxer.HealthyWithVS\djfoxer.HealthyWithVS\StatusBar\CommandShowTomatoStatusBar.cs:line 64   at djfoxer.HealthyWithVS.CommandShowTomatoStatusBarPackage.Initialize() in C:\Users\Scorpion\Desktop\healthyWithVS-master\djfoxer.HealthyWithVS\djfoxer.HealthyWithVS\StatusBar\CommandShowTomatoStatusBarPackage.cs:line 76   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
-- | --

**Comment by djfoxer** [comment]
Thank you, I need to investigate it deeper and install VS2019.

**Comment by djfoxer** [comment]
Fixed in 0.5 version, commit: https://github.com/djfoxer/healthyWithVS/commit/0299f0b248e829c7085d95dc4cc5b35a7887322b
